package tl222xy_assign1.fibonacci;

public class Fibonacci {

    public static void main(String[] args) {
        // Each new term in the Fibonacci sequence is generated by adding the previous two terms. By
        //starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
        //Write a program Fibonacci.java that prints a Fibonacci sequence starting with 1 and 2 and
        //whose values do not exceed one thousand. The program should also compute and print a sum of
        //the odd-valued terms in the required Fibonacci sequence.
    }
}